#ifndef SETS_H
#define SETS_H

#define RGA_NONE 0
#define RGA_INITIAL 1
#define RGA_PRECOLOURED 2
#define RGA_SIMPLIFY_WORKLIST 3
#define RGA_FREEZE_WORKLIST 4
#define RGA_SPILL_WORKLIST 5
#define RGA_SPILLED_NODES 6
#define RGA_COALESCED_NODES 7
#define RGA_COLOURED_NODES 8
#define RGA_SELECT_STACK 9

#define RGA_COALESCED_MOVES 1
#define RGA_CONSTRAINED_MOVES 2
#define RGA_FROZEN_MOVES 3
#define RGA_WORKLIST_MOVES 4
#define RGA_ACTIVE_MOVES 5

#endif
